### ISSUE TITLE
is this project active?

### ISSUE THREAD

**Issue by eldoralabs** [af/bs-d3#12]
I'm interested in helping this project out.  Is it active?  If not, i'll fork it and carry on, but I'm reaching out first.  Let me know!  You've done some cool work!

**Comment by af** [comment]
Hi, it's safe to say I'm not very active on this any more :). I haven't really had time for Reason/BS in the last few months. I'd encourage you to fork and carry on with it, if you make a bunch of progress we could merge the repos or I could direct people to your fork from the readme 👍
