### ISSUE TITLE
Up and Running

### ISSUE THREAD

**Issue by mmport80** [af/bs-d3#8]
I tried this package, but failed to get it up and running.

I intalled, using `yarn add af/bs-d3 d3` but see this error message on the web page's script which I am trying to use this:

`Uncaught Error: Cannot find module 'D3/src/D3_Scale.js'`

Other D3 libs seem to be OK.. Any ideas?

**Comment by af** [comment]
Hi,

Sorry to hear of the problem– which version of `bs-platform` and node do you have installed?

That error is coming from the devtools console?

**Comment by af** [comment]
Closing this out, but will re-open with more details and repro steps
